### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by rrjohnson** [awslabs/aws-serverless-workshops#12]
On

https://github.com/awslabs/aws-serverless-workshops/tree/master/WebApplication

the links at the bottom of Readme.MD for 

* RESTful APIs
* Persistence

are broken.

**Comment by jpignata** [comment]
Thanks! Looks like this was addressed in https://github.com/awslabs/aws-serverless-workshops/commit/19a8731ee8457991d80825ad1f60c185163aab0a#diff-d8bf76e3fa720dfb28f69b45df836ffe.
