### ISSUE TITLE
Missing "Save Changes" in Module 2, Step 2

### ISSUE THREAD

**Issue by BillRaymond** [awslabs/aws-serverless-workshops#13]
In Module 2, Step 2 of the WildRydes app, it ends with Step 6 that tells you to make note of the App Client ID. I believe there should be a Step 7 where you click the Save Changes button.

**Comment by jpignata** [comment]
Thanks for opening this! The app is actually created when you click **Create app** in step 5 and **Save changes** is effectively a no-op so I think this is safe to leave as is. Please let me know if you find that I'm incorrect on that.
