### ISSUE TITLE
Cannot delete wildrydes-unicorn-api CloudFormation Stack

### ISSUE THREAD

**Issue by PC-JBuchanan** [awslabs/aws-serverless-workshops#20]
In DevOps/9_CleanUp/README.md Step 4. Module 1 Cleanup, the wildrydes-unicorn-api stack cannot be deleted. An error is given due to the role WildRydesUnicornApiCloudFormation being removed in the previous cleanup step.

**Comment by samdengler** [comment]
@PC-JBuchanan Thanks for the notification.  This will be corrected in an upcoming release.
