### ISSUE TITLE
Potential unresolved issues with the Web Application workshop

### ISSUE THREAD

**Issue by jpignata** [awslabs/aws-serverless-workshops#23]
We saw a couple of issues with the Web Application workshop that might need to be addressed:

- The Esri map would not render in certain, older versions of Chrome (~51) on Windows. This seems to be a bug that was fixed. To address, we should be prescriptive about which versions of Firefox and Chrome can be used for this workshop.
- ~~We had several participants who experienced timeouts through the API Gateway endpoint to the Lambda function. I personally experienced this myself running through the workshop. For these cases we saw the functions timing out in CloudWatch Logs. In each case we increased the timeout above the default 3 seconds and the participants were able to proceed. I'm baffled as to why this was happening as the function does very little and usually executes within 100ms. There was very shoddy connectivity during the workshop, so one possibility that crossed my mind is that slow HTTP readers cause the Lambda function to run longer than they should, but this works against my understanding of how the API Gateway and Lambda integration works and I can't reproduce it artificially. To address, we should try to suss out what was happening here and create an instructors guide in the repo with common potential pitfalls like this if necessary.~~
- Many participants' directions were not collapsed due to their browser not supporting those markup tags. To address, we should be prescriptive about which versions of Firefox and Chrome can be used for this workshop.
- Some participants do not understand that they could expand the step-by-step directions and get stuck. To address, we should make the structure and directions clear in the presentation element of the workshop.
- Many participants used the CloudFormation template because they thought it was the first step but actually wanted to go through the steps. To address, we should be very clear that this is just a potential bypass for the module. Potentially we could move this section to the bottom of the directions and link to it from the top.
- As usual, the CLI setup was somewhat challenging and consumed the first 30 minutes of the workshop for a large number of participants. To address, we should put together a preliminary lab that includes installing and testing the CLI with appropriate credentials.

**Comment by jpignata** [comment]
I'm fairly certain the timeout condition crossed-out above is a red herring and the actual issue centers around participants missing steps in the setup which causes an unexpected exception to be thrown in the Lambda function. I've opened up https://github.com/awslabs/aws-serverless-workshops/pull/29 to return more useful feedback to participants who hit this condition.

**Comment by vegasbrianc** [comment]
I'm also experiencing the Ersi map not rendering. I'm using a Mac and tried with the latest versions of Chrome 59.0.3071.115  and Safari 10.1.1 (12603.2.4)

**Comment by forrest-akin** [comment]
I've completed all steps, successfully validating with each one, but when I try to request a ride at the end I get the following.
browser console:
```
Response received from API:  { errorMessage: "RequestId: 99c6fc8b-6dc1-11e7-bd91-47cf8f403e4f Process exited before completing request" }       ride.js:44
```
lambda logs:
```
event = {
    "PickupLocation": {
        "Latitude": 47.602662220817905,
        "Longitude": -122.32836776733186
    }
}
...
TypeError: Cannot read property 'authorizer' of undefined at exports.handler (/var/task/index.js:27:30)
```
Why is my event object missing the authorizer and where is that supposed to be coming from?

**Comment by jpignata** [comment]
Is it possible your function is not configured to use Cognito User Pools
for authorization?

**Comment by forrest-akin** [comment]
I figured out the problem going back through the steps in the final module. I had missed the step to **Check the box for Use Lambda Proxy integration** under **3. Create a new resource and method** . After fixing that and redeploying my API, I was able to get it working. Great workshop!

**Comment by jpignata** [comment]
Closing for now as I assume the web application workshop will get an overhaul in 2018.

**Comment by vijayjb** [comment]
Had the same issue, forgot to enable Lambda Proxy integration under 3.

**Comment by gphilipp** [comment]
Same for me 😱
