### ISSUE TITLE
Image disagrees with text in /DevOps/2_ContinuousDeliveryPipeline/README.md

### ISSUE THREAD

**Issue by pc-mreeves** [awslabs/aws-serverless-workshops#26]
The image /DevOps/2_ContinuousDeliveryPipeline/images/codepipeline-add-2.png should be corrected to have its Template input value changed from:
`MyAppBuild::output.yaml` to: `MyAppBuild::app-sam-output.yaml` to agree with the text that says:
"Enter MyAppBuild::app-sam-output.yaml for Template". 

I missed that step.

**Comment by samdengler** [comment]
@pc-mreeves - apologies for the delay.  The workshop has been updated today to use CodeStar, which has replaced this screenshot in Module 2.  I'll close for now.  Please check out the updates, and let me know if you have any feedback on the new format.  Thanks!
