### ISSUE TITLE
Minor: inconsistency in Lambda name between module 3 and 4

### ISSUE THREAD

**Issue by KeiichiTheOtaku** [awslabs/aws-serverless-workshops#32]
In module 3, the suggested Lambda name is "RequestUnicorn", and then in module 4 it says to use the "RequestRide" lambda you created in the previous module.

Since the API Gateway /ride Resource Action setup doesn't provide a dropdown of options, but has you type in your Lambda name, it would be nice if the names in the instructions were consistent.

Thanks.

**Comment by jpignata** [comment]
Thanks! There's a pending pull request (https://github.com/awslabs/aws-serverless-workshops/pull/30) to resolve this pending review and feedback from @mikedeck. We'll leave this issue opened until the inconsistency is fixed.

**Comment by KeiichiTheOtaku** [comment]
Cool, thanks!

**Comment by mikedeck** [comment]
This should be fixed now. Thanks!
