### ISSUE TITLE
Issue with the instructions for Module 4 for the WebApplication

### ISSUE THREAD

**Issue by volpem63** [awslabs/aws-serverless-workshops#50]
The instructions for creating a customer authorizer says Ensure the identity token sources is set to method.request.header.Authorization.  This breaks the site and should be set to just "Authorization"

![image](https://user-images.githubusercontent.com/14116678/30604991-867a3cb6-9d3a-11e7-9846-4745a3795a28.png)

**Comment by mikedeck** [comment]
Thanks for reporting this. It is now fixed.
