### ISSUE TITLE
Final Test Not Working

### ISSUE THREAD

**Issue by nburdett19** [awslabs/aws-serverless-workshops#51]
Hello, 

I went throught the entire workshop step by step and at the end when requesting a unicorn, i get an error of. Are there any ways to debug this?
![image](https://user-images.githubusercontent.com/16125611/30938626-8c63b03e-a38f-11e7-9222-09a507374d24.png)

**Comment by Jefdem1** [comment]
I was able to resolve this by changing this step
 Module 4 f.Ensure that the Identity token source is set to method.request.header.Authorization
Instead of method.request.header.Authorization i just used authorization

**Comment by Seblat5ch** [comment]
Jefdem1@ you sir are a legend. 
![image](https://user-images.githubusercontent.com/18715670/31166051-a57b1450-a8ed-11e7-880f-07c88eb78d64.png)
