### ISSUE TITLE
error in DataProcessing workshop

### ISSUE THREAD

**Issue by remster85** [awslabs/aws-serverless-workshops#55]
Hello,

The [Function WildRydesFileProcessor](https://github.com/awslabs/aws-serverless-workshops/blob/master/DataProcessing/1_FileProcessing/lambda/WildRydesFileProcessor/index.js) is failing at  _event.Records.map()_ call.

**Cannot read property 'map' of undefined.**

I have submitted the following input  as test

> {"Name":"Shadowfax","StatusTime":"2016-02-12 00:00:00.000","Distance":1317,"MinMagicPoints":146,"MaxMagicPoints":149,"MinHealthPoints":144,"MaxHealthPoints":149}

and

> {
  "Records": [
 {"Name":"Shadowfax","StatusTime":"2016-02-12 00:00:00.000","Distance":1317,"MinMagicPoints":146,"MaxMagicPoints":149,"MinHealthPoints":144,"MaxHealthPoints":149}
  ]
}

thanks for helping.

**Comment by jpignata** [comment]
The file processor expects an S3 notification event indicating where the code should grab an object to process for processing and writing into DynamoDB. See [the documentation][docs] for an example of a sample event.

[docs]: http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html
