### ISSUE TITLE
Unable to locate credentials?

### ISSUE THREAD

**Issue by beesman** [awslabs/aws-serverless-workshops#61]
Hi,

When I attempt to execute the awscli command to upload the website assets to my S3 bucket I get the following error: 
> Fatal error: Unable to locate credentials

I have replaces the default bucket name & bucket region with my own.

Can you please advise? Thanks

**Comment by jpignata** [comment]
Please see [Configuring the AWS CLI][conf-cli] for more details on how to configure the credentials.

[conf-cli]: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
