### ISSUE TITLE
Can't execute Lambda function

### ISSUE THREAD

**Issue by jasoncal108** [awslabs/aws-serverless-workshops#8]
When executing the Lambda function for subscribing an email, I receive the following error
{
  "errorMessage": "RequestId: ffff-ffffff-fffffffffffffff Process exited before completing request"
}

TypeError: Cannot read property 'forEach' of undefined
    at exports.handler.event.Records.forEach (/var/task/index.js:5:16)

**Comment by tjhsiao2017** [comment]
I believe your error is related with missing testing parameter.

But most important is the instruction is missing to mention adding Permission 'AWSLambdaDynamoDBExecutionRole' to the SESRole.

**Comment by jpignata** [comment]
Let us know if you still need any help.
